
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import subprocess
from datetime import datetime
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

import psycopg2

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0"


def show_new_window():
    window.destroy()
    subprocess.run(['python', '../HomeGUI/Home.py'])

def check_fields():
    first_name = entry_1.get("1.0", "end-1c")
    last_name = entry_7.get("1.0", "end-1c")
    user_id_str = entry_6.get("1.0", "end-1c")
    email = entry_5.get("1.0", "end-1c")
    birth_date_str = entry_4.get("1.0", "end-1c")
    phone_number = entry_3.get("1.0", "end-1c")
    country = entry_2.get("1.0", "end-1c")
    # Try converting the ID and birth date to the correct type

    if not all([first_name, last_name, user_id_str, email, birth_date_str, phone_number, country]):
        messagebox.showerror("Error", "All fields must be filled")
        return

    try:
        user_id = int(user_id_str)
    except ValueError:
        messagebox.showerror("Error", "Invalid ID format")
        return

    try:
        birth_date = datetime.strptime(birth_date_str, "%Y-%m-%d")
    except ValueError:
        messagebox.showerror("Error", "Invalid birth date format")
        return


        # Convert user_id to int
    user_id = int(user_id_str)

    # Convert birth_date to date
    birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d').date()

    # Connect to the database
    conn = psycopg2.connect(database="test", user='postgres', password='mrrobot', host='localhost')

    # Create a cursor object
    cur = conn.cursor()

    # Insert user inputs into the database
    cur.execute("""INSERT INTO student (id, first_name, last_name, email, date_of_birth, contact_number, country) 
                       VALUES (%s, %s, %s, %s, %s, %s, %s)""",
                (user_id, first_name, last_name, email, birth_date, phone_number, country))

    # Commit changes and close
    conn.commit()
    cur.close()
    conn.close()

    messagebox.showinfo("Success", "Student registered successfully")
    show_new_window()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Student Management App")
window.geometry("1280x832")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 832,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    416.0,
    image=image_image_1
)

canvas.create_text(
    169.0,
    69.0,
    anchor="nw",
    text="WELCOME TO STUDENT MANAGEMENT SYSTEM",
    fill="#1E1E1E",
    font=("Inter", 40 * -1)
)

canvas.create_rectangle(
    199.0,
    194.0,
    1080.0,
    700.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    408.0229034423828,
    316.6984405517578,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=243.0,
    y=300.0,
    width=330.0458068847656,
    height=31.396881103515625
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    408.0229034423828,
    561.6984405517578,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=243.0,
    y=545.0,
    width=330.0458068847656,
    height=31.396881103515625
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    828.0228881835938,
    476.69844245910645,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=663.0,
    y=460.0,
    width=330.0457763671875,
    height=31.39688491821289
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    408.0229034423828,
    476.69844245910645,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=243.0,
    y=460.0,
    width=330.0458068847656,
    height=31.39688491821289
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    828.0228881835938,
    393.69844245910645,
    image=entry_image_5
)
entry_5 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=663.0,
    y=377.0,
    width=330.0457763671875,
    height=31.39688491821289
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    408.0229034423828,
    393.69844245910645,
    image=entry_image_6
)
entry_6 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=240.0,
    y=377.0,
    width=336.0458068847656,
    height=31.39688491821289
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    828.0228881835938,
    316.6984405517578,
    image=entry_image_7
)
entry_7 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=663.0,
    y=300.0,
    width=330.0457763671875,
    height=31.396881103515625
)

canvas.create_text(
    655.0,
    260.0,
    anchor="nw",
    text="Last Name",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    235.0643310546875,
    343.12109375,
    anchor="nw",
    text="ID",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    654.9561767578125,
    343.12109375,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    235.0643310546875,
    420.3681640625,
    anchor="nw",
    text="Birth Date",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    235.0,
    260.0,
    anchor="nw",
    text="First Name",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: check_fields(),
    relief="flat"
)
button_1.place(
    x=277.1393737792969,
    y=608.742431640625,
    width=697.24365234375,
    height=58.257598876953125
)

canvas.create_text(
    654.9561767578125,
    420.7878723144531,
    anchor="nw",
    text="Phone Number",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    235.0643310546875,
    503.671630859375,
    anchor="nw",
    text="Country",
    fill="#000000",
    font=("Poppins Regular", 25 * -1)
)

canvas.create_text(
    500.0,
    210.0,
    anchor="nw",
    text="Registration Form",
    fill="#000000",
    font=("Poppins Regular", 32 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: show_new_window(),
    relief="flat"
)
button_2.place(
    x=65.0,
    y=725.0,
    width=243.0,
    height=43.7293701171875
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: window.destroy(),
    relief="flat"
)
button_3.place(
    x=965.0,
    y=725.0,
    width=243.0,
    height=43.7293701171875
)

window.resizable(False, False)
window.mainloop()
